ECommerceOrderManagement/Areas/Admin/Controllers/BannerController.cs
using EOMS.DataAccess.Repository.IRepository;
using EOMS.Utility;
using EOMS.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Drawing;
using Microsoft.Extensions.Hosting;
using System.Collections.Generic;

namespace ECommerceOrderManagement.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class BannerController : Controller
    {
        private readonly IBannerRepository _bannerRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public BannerController(IBannerRepository bannerRepository, IWebHostEnvironment webHostEnvironment)
        {
            _bannerRepository = bannerRepository;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            List<Banner> objBannerList = _bannerRepository.GetAll().ToList();
            return View(objBannerList);
        }

        public IActionResult Upsert(int? id)
        {
            Banner banner = new Banner();
            if (id == null)
            {
                return View(banner);
            }
            else
            {
                banner = _bannerRepository.GetT(b => b.Id == id);
                if (banner == null)
                {
                    return NotFound();
                }
            }
            return View(banner);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Banner banner, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string bannerPath = Path.Combine(wwwRootPath, @"images/banner");

                    if (!string.IsNullOrEmpty(banner.ImageUrl))
                    {
                        //delete the old image

                        var oldBannerPath = Path.Combine(wwwRootPath, banner.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldBannerPath))
                        {
                            System.IO.File.Delete(oldBannerPath);
                        }

                    }

                    using (var filestream = new FileStream(Path.Combine(bannerPath, fileName), FileMode.Create))
                    {
                        file.CopyTo(filestream);
                    }
                    banner.ImageUrl = @"/images/banner/" + fileName;
                }

                if (banner.Id == 0)
                {
                    banner.CreatedDate = DateTime.Now;
                    _bannerRepository.Add(banner);
                    TempData["success"] = "Banner saved successfully";
                }
                else
                {
                    _bannerRepository.Update(banner);
                    TempData["success"] = "Banner updated successfully";
                }
                _bannerRepository.Save();
                return RedirectToAction("Index");

            }
            TempData["error"] = "Failed to save banner. Please check the form and try again.";
            return View(banner);
        }

        [HttpPost,ActionName("Delete")]
        public IActionResult Delete(int id)
        {
            var banner = _bannerRepository.GetT(b => b.Id == id);
            if (banner == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, banner.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }

            _bannerRepository.Remove(banner);
            _bannerRepository.Save();
            return Json(new { success = true, message = "Delete successful" });
        }
    }
}

ECommerceOrderManagement/Areas/Admin/Controllers/CategoryController.cs
using EOMS.DataAccess.Data;
using Microsoft.AspNetCore.Mvc;
using EOMS.Models;
using EOMS.DataAccess.Repository.IRepository;
using EOMS.DataAccess.Repository;
using EOMS.Utility;
using Microsoft.AspNetCore.Authorization;

namespace ECommerceOrderManagement.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles=SD.Role_Admin)]
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;

        public CategoryController(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }
        public IActionResult Index()
        {
            List<Category> objCategoryList = _categoryRepository.GetAll().ToList();
            return View(objCategoryList);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Category obj)
        {
           
            if (ModelState.IsValid)
            {
                _categoryRepository.Add(obj);
                _categoryRepository.Save();
                TempData["success"] = "Category created successfully";
                return RedirectToAction("Index");
            }
            return View();

        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category categoryFromDb = _categoryRepository.Get(u => u.Id == id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }

            return View(categoryFromDb);
        }
        [HttpPost]
        public IActionResult Edit(Category obj)
        {

            if (ModelState.IsValid)
            {
                _categoryRepository.Update(obj);
                _categoryRepository.Save();
                TempData["success"] = "Category updated successfully";

                return RedirectToAction("Index");
            }
            return View(obj);

        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category categoryFromDb = _categoryRepository.Get(u => u.Id == id);

            if (categoryFromDb == null)
            {
                return NotFound();
            }

            return View(categoryFromDb);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
            Category? obj = _categoryRepository.Get(u => u.Id == id);

            if (obj == null)
            {
                return NotFound();
            }
            _categoryRepository.Remove(obj);
            _categoryRepository.Save();
            TempData["success"] = "Category deleted successfully";

            return RedirectToAction("Index");

        }
    }
}

ECommerceOrderManagement/Areas/Admin/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using EOMS.DataAccess.Repository.IRepository;
using EOMS.Models.ViewModels;
using ECommerceOrderManagement.GlobalExceptionHandler;
using EOMS.Utility;
using Microsoft.AspNetCore.SignalR;
using Microsoft.AspNetCore.Identity;
using EOMS.Models;
using System.Security.Claims;

namespace ECommerceOrderManagement.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class OrderController : Controller
    {
        private readonly IOrderHeaderRepository _orderHeaderRepository;
        private readonly IOrderDetailRepository _orderDetailRepository;
        private readonly IHubContext<SignalR> _hubContext;
       

        public OrderController(IOrderHeaderRepository orderHeaderRepository, IOrderDetailRepository orderDetailRepository, IHubContext<SignalR> hubContext)
        {
            _orderHeaderRepository = orderHeaderRepository;
            _orderDetailRepository = orderDetailRepository;
            _hubContext = hubContext;
            
        }

        public IActionResult Index()
        {
            var allOrders = _orderHeaderRepository.GetAll(includeProperties: "ApplicationUser");
            var orderList = allOrders.Select(o => new OrderVM
            {
                OrderHeader = o,
                OrderDetails = _orderDetailRepository.GetAll(d => d.OrderHeaderId == o.Id, includeProperties: "Product")
            }).ToList();

            return View(orderList);
        }

        public async Task<IActionResult> UpdateStatus(int orderId, string status)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var order = _orderHeaderRepository.Get(orderId);

            if (order == null)
            {
                throw new OrderNotFoundException($"Order with ID {orderId} was not found.");
            }

            var allowedTransitions = new Dictionary<OrderStatus, List<OrderStatus>>
    {
        { OrderStatus.Approved, new List<OrderStatus> { OrderStatus.Processed, OrderStatus.Cancelled } },
        { OrderStatus.Processed, new List<OrderStatus> { OrderStatus.Approved, OrderStatus.Shipped, OrderStatus.Cancelled } },
        { OrderStatus.Shipped, new List<OrderStatus> { OrderStatus.Processed, OrderStatus.Delivered, OrderStatus.Cancelled } },
        { OrderStatus.Delivered, new List<OrderStatus> { OrderStatus.Shipped, OrderStatus.Cancelled } }
    };

            if (order.OrderStatus == OrderStatus.Cancelled)
            {
                TempData["error"] = "Cannot update status after cancellation.";
                return RedirectToAction(nameof(Index));
            }

            if (allowedTransitions.TryGetValue(order.OrderStatus, out var possibleStatuses) && possibleStatuses.Contains((OrderStatus)Enum.Parse(typeof(OrderStatus), status)))
            {
                _orderHeaderRepository.UpdateStatus(orderId, status);
                _orderHeaderRepository.Save();

                // Notify the client about the status update
                await _hubContext.Clients.User(order.ApplicationUserId).SendAsync("ReceiveStatusUpdate", status, order.Id);
            }
            else
            {
                // Invalid status transition
                TempData["error"] = "Invalid status transition.";
            }

            return RedirectToAction(nameof(Index));
        }


    }
}

ECommerceOrderManagement/Areas/Customer/Controllers/CartController.cs
using EOMS.DataAccess.Repository.IRepository;
using EOMS.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using EOMS.Utility;
using EOMS.Models;

namespace ECommerceOrderManagement.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize(Roles = SD.Role_Customer)]
    public class CartController : Controller
    {
        private ICartRepository _cartRepository;
        private IApplicationUserRepository _applicationUserRepository;
        private IOrderHeaderRepository _orderHeaderRepository;
        private IOrderDetailRepository _orderDetailRepository;
        public CartVM vm { get; set; }

        public CartController(ICartRepository cartRepository, IApplicationUserRepository applicationUserRepository, IOrderHeaderRepository orderHeaderRepository, IOrderDetailRepository orderDetailRepository)
        {
            _cartRepository = cartRepository;
            _applicationUserRepository = applicationUserRepository;
            _orderHeaderRepository = orderHeaderRepository;
            _orderDetailRepository = orderDetailRepository;
        }

        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);


            vm = new CartVM()
            {
                ListOfCart = _cartRepository.GetAll(x => x.ApplicationUserId == claim.Value, includeProperties: "Product"),
                OrderHeader = new EOMS.Models.OrderHeader()

            };

            foreach (var item in vm.ListOfCart)
            {
                vm.OrderHeader.OrderTotal += (item.Product.Price * item.Count);
            }
            return View(vm);
        }
        [HttpPost]
        public IActionResult Plus(int id)
        {
            var cart = _cartRepository.GetT(x => x.Id == id);
            _cartRepository.IncrementCartItem(cart, 1);
            _cartRepository.Save();

            var updatedCart = _cartRepository.GetAll(x => x.ApplicationUserId == cart.ApplicationUserId, includeProperties: "Product");
            var total = updatedCart.Sum(x => x.Product.Price * x.Count);

            return Json(new { success = true, cart = updatedCart, total });
        }


        [HttpPost]
        public IActionResult Minus(int id)
        {
            var cart = _cartRepository.GetT(x => x.Id == id);

            if (cart.Count <= 1)
            {
                _cartRepository.Delete(cart);
            }
            else
            {
                _cartRepository.DecrementCartItem(cart, 1);
            }

            _cartRepository.Save();

            var updatedCart = _cartRepository.GetAll(x => x.ApplicationUserId == cart.ApplicationUserId, includeProperties: "Product");
            var total = updatedCart.Sum(x => x.Product.Price * x.Count);

            return Json(new { success = true, cart = updatedCart, total });
        }


        [HttpPost]
        public IActionResult Delete(int id)
        {
            var cart = _cartRepository.GetT(x => x.Id == id);
            _cartRepository.Delete(cart);
            _cartRepository.Save();

            var updatedCart = _cartRepository.GetAll(x => x.ApplicationUserId == cart.ApplicationUserId, includeProperties: "Product");
            var total = updatedCart.Sum(x => x.Product.Price * x.Count);

            return Json(new { success = true, cart = updatedCart, total });
        }

        public IActionResult Summary()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);


            vm = new CartVM()
            {
                ListOfCart = _cartRepository.GetAll(x => x.ApplicationUserId == claim.Value, includeProperties: "Product"),
                OrderHeader = new EOMS.Models.OrderHeader()

            };
            vm.OrderHeader.ApplicationUser = _applicationUserRepository.GetT(x => x.Id == claim.Value);

            vm.OrderHeader.Name = vm.OrderHeader.ApplicationUser.Name;

            vm.OrderHeader.Address = vm.OrderHeader.ApplicationUser?.Address;

            vm.OrderHeader.City = vm.OrderHeader.ApplicationUser?.City;

            vm.OrderHeader.State = vm.OrderHeader.ApplicationUser?.State;

            vm.OrderHeader.ZipCode = vm.OrderHeader.ApplicationUser?.ZipCode;

            foreach (var item in vm.ListOfCart)
            {
                vm.OrderHeader.OrderTotal += (item.Product.Price * item.Count);
            }
            return View(vm);
        }

        [HttpPost]
        public IActionResult Summary(CartVM vm)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            // Retrieve the current user's application user object
            var applicationUser = _applicationUserRepository.GetT(x => x.Id == claim.Value);

            // Update the user's address
            applicationUser.Address = vm.OrderHeader.Address;
            applicationUser.City = vm.OrderHeader.City;
            applicationUser.State = vm.OrderHeader.State;
            applicationUser.ZipCode = vm.OrderHeader.ZipCode;

            // Save the updated address in the database
            _applicationUserRepository.Update(applicationUser);
            _applicationUserRepository.Save();

            // Proceed with placing the order
            vm.ListOfCart = _cartRepository.GetAll(x => x.ApplicationUserId == claim.Value, includeProperties: "Product");
            vm.OrderHeader.OrderStatus = OrderStatus.Approved;
            vm.OrderHeader.DateOfOrder = DateTime.Now;
            vm.OrderHeader.ApplicationUserId = claim.Value;

            foreach (var item in vm.ListOfCart)
            {
                vm.OrderHeader.OrderTotal += (item.Product.Price * item.Count);
            }
            _orderHeaderRepository.Add(vm.OrderHeader);
            _orderHeaderRepository.Save();

            foreach (var item in vm.ListOfCart)
            {
                OrderDetail orderDetail = new OrderDetail()
                {
                    ProductId = item.ProductId,
                    OrderHeaderId = vm.OrderHeader.Id,
                    Count = item.Count,
                    Price = (double)item.Product.Price
                };
                _orderDetailRepository.Add(orderDetail);
                _orderDetailRepository.Save();
            }

            // Clear the cart
            _cartRepository.DeleteRange(vm.ListOfCart);
            _cartRepository.Save();

            return RedirectToAction("OrderSuccess", new { id = vm.OrderHeader.Id });
        }


        public IActionResult OrderSuccess(int id)
        {
            var order = _orderHeaderRepository.GetT(x => x.Id == id);
            return View(order); 
        }
    }
}

ECommerceOrderManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @{
        ViewData["Title"] = "Ecommerce";
    }
    <title>@ViewData["Title"] - Coditas App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/ECommerceOrderManagement.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <style>
        /* Ensure footer is at the bottom */
        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }

        /* Main content takes up available space */
        main {
            flex: 1;
        }

        /* Footer styling */
        footer {
            color: white; /* Change text color to white */
            margin-top: auto;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ECommerceOrderManagement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        @if (User.Identity.IsAuthenticated && !User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index"><i class="bi bi-cart3"></i></a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="MyOrders">My Orders</a>
                            </li>
                        }
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="adminDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Manage
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="adminDropdown">
                                    <li><a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Categories</a></li>
                                    <li><a class="dropdown-item" asp-area="Admin" asp-controller="Products" asp-action="Index">Products</a></li>
                                    <li><a class="dropdown-item" asp-area="Admin" asp-controller="Banner" asp-action="Index">Banners</a></li>
                                    <li><a class="dropdown-item" asp-area="Admin" asp-controller="Order" asp-action="Index">Orders</a></li>
                                </ul>
                            </li>
                        }
                    </ul>
                    <form class="d-flex" asp-controller="Home" asp-action="Search">
                        <input name="query" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-light" type="submit">
                            <i class="bi bi-search"></i> 
                        </button>
                    </form>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<style>
    
    .navbar-nav .nav-link {
        color: white !important; 
    }

    .dropdown-menu {
        background-color: #006699; 
    }

        .dropdown-menu .dropdown-item {
            color: white !important; 
        }

            .dropdown-menu .dropdown-item:hover {
                background-color: #006699; 
                color: white; 
            }
</style>

ECommerceOrderManagement/Views/Shared/_Notification.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        toastr.options = {
            "positionClass": "toast-top-right"
        };

        if ('@TempData["success"]' !== '') {
            toastr.success('@TempData["success"]');
        }
        if ('@TempData["error"]' !== '') {
            toastr.error('@TempData["error"]');
        }
    });
</script>